# ABILITA LE IMPOSTAZIONI SEPARATE PER LISTENER
per_listener_settings true

# Internal listener (no auth for Gateway components)
listener 1883
allow_anonymous true

# Secure listener with mTLS for sensors
listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/broker.crt
keyfile /mosquitto/certs/broker.key
require_certificate true
use_identity_as_username true
acl_file /mosquitto/config/acl

# Logging
log_dest stdout
log_type all

# Persistence
persistence true
persistence_location /mosquitto/data/