server {
    listen 443 ssl;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr info;

    ssl_certificate /etc/nginx/certs/provisioner.crt;
    ssl_certificate_key /etc/nginx/certs/provisioner.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_verify_client off;

    # Enable dynamic DNS resolution for every request
    resolver 127.0.0.11 valid=5s;
    set $upstream http://provisioner:5000;

    location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
